apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: statsig-debug
  networking:
    # Disable default CNI so we can install Cilium.
    disableDefaultCNI: true
    # Enable pod subnet for Cilium.
    podSubnet: "10.244.0.0/16"
    # Enable service subnet.
    serviceSubnet: "10.96.0.0/16"
  nodes:
    - role: control-plane
      extraPortMappings:
        # HTTP ingress.
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # HTTPS ingress.
        - containerPort: 443
          hostPort: 443
          protocol: TCP
    - role: worker
